"""add_ticket_id_to_transaction

Revision ID: 0aaa39c06c83
Revises:     7738bf9c9793
Created at:  2026-04-04 06:33:37.979994+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0aaa39c06c83'
down_revision: str | None = '7738bf9c9793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ticket_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_transaction_ticket_id'), 'transaction', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'ticket', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_ticket_id'), table_name='transaction')
    op.drop_column('transaction', 'ticket_id')
    # ### end Alembic commands ###
